---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: 18.144.87.142:8123/nobody/web:1
        imagePullPolicy: Always
        name: myweb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb
  type: NodePort
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxOC4xNDQuODcuMTQyOjgxMjMiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2Y1hkbGNqRXlNelE9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy42IChsaW51eCkiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
